apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - healthy.sh
          initialDelaySeconds: 20
          periodSeconds: 10
---

apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    #It is possible to share the same Load Balancer across multiple
    #services as long as the services do not use the same ports
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
  - port: 5050
    targetPort: 5050
