apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21 #add more port to transfert data <range> √
        - containerPort: 2100
        - containerPort: 2101
        livenessProbe:
          exec:
            command:
            - sh
            - healthy.sh
          initialDelaySeconds: 15
          periodSeconds: 5
apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - name: ftps
    port: 21
    targetPort: 21
  - name: data-tranf
    port: 2100
    targetPort: 2100
  - name: data-tranf2
    port: 2101
    targetPort: 2101
